bind r source-file ~/.config/tmux/tmux.conf \; display "tmux.conf Reloaded!"

set-option -g prefix C-s
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",*256col*:Tc"
set-option -g default-command fish
set-option -s escape-time 10
set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g mouse on
set-window-option -g mode-keys vi # VIM-like copy mode

# PANE NAVIGATION
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 

# COLORS
DARK_TEAL="#0E3733"
PALE_TEAL="#A1E8E2"
CREAM="#E8DEC9"
LATTE="#B3A180"
MOCHA="#655843"
DARK_MOCHA="#2C2721"
BLACK="#000000"

# MESSAGE STYLE
set-option -g message-style "bg=$BLACK,fg=$PALE_TEAL"
set-option -g message-command-style "bg=$BLACK,fg=$PALE_TEAL"

# PANE STYLE
set-option -g pane-border-style "bg=default,fg=$DARK_TEAL"
set-option -g pane-active-border-style "bg=default,fg=$PALE_TEAL"

# STATUS BAR
set-option -g status on
set-option -g status-interval 5
set-option -g status-justify left
set-option -g status-style "bg=$BLACK"

status_time="#[fg=$MOCHA]%H:%M"
status_right=" 󱗼 #[fg=$MOCHA](◍ㅈ◍=マ#[fg=$DARK_MOCHA]󱗼 $status_time #[fg=$DARK_MOCHA]󰚉 "

set-option -g status-left " #S 󱗼 "
set-option -g status-left-length 10
set-option -g status-left-style "fg=$LATTE"
set-option -g status-right "$status_right"
set-option -g status-right-style "fg=$DARK_MOCHA"

win_status="#[bg=$DARK_MOCHA,fg=$BLACK] #I #[bg=$BLACK,fg=$DARK_MOCHA] #W #[fg=$DARK_MOCHA]󰚉"
win_status_current="#[fg=$BLACK,bg=$MOCHA] #I #[bg=$BLACK,fg=$CREAM] #W #[fg=$MOCHA]󰚉"

set-window-option -g window-status-separator "#[fg=$DARK_MOCHA]  "
set-window-option -g window-status-format "$win_status"
set-window-option -g window-status-style "fg=$MOCHA"
set-window-option -g window-status-current-format "$win_status_current"
set-window-option -g window-status-current-style "bg=$BLACK"


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
